[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 10737418240  # 10GB in bytes
maxMessageSize = 10737418240  # 10GB in bytes

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true
